name: Go

on:
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/ci-backend.yml"
      - "*.go"
      - "!**.md"
  pull_request:
    branches: ["main"]
    paths:
      - ".github/workflows/ci-backend.yml"
      - "*.go"
      - "!**.md"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GO_VERSION: 1.21.5
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: checkout
        uses: actions/checkout@v4

      - name: govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-version-input: ${{ env.GO_VERSION }}
          go-package: ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.55
          # Optional: working directory, useful for monorepos
          working-directory: .

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.55
          # Optional: working directory, useful for monorepos
          working-directory: .

      - name: Test
        working-directory: .
        run: go test -v ./...

      - name: Build
        working-directory: .
        run: CGO_ENABLED=0 go build -ldflags="-s"  -v ./...
